//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.24 at 08:15:15 AM UTC 
//


package com.leunca.ndc.advance;

public class VoiceGuidanceType {
	
	private final String Identifier = "<"; 

    private String voiceGuidanceLanguageID;

    public String getVoiceGuidanceLanguageID() {
        return voiceGuidanceLanguageID;
    }
}
